### PR TITLE
netstandard1.3 changes

### PR DESCRIPTION
**Pull request by rprouse**
Part of PR nunit/nunit#1545 by @jasonwilliams200OK cherry picked off his fork

**Do not merge yet** I have additional changes I want to do, but wanted to see the history and diffs here.

### CODE REVIEW

**Comment by ghost** [comment]
@rprouse, can we also add `.travis.yml` to test on Ubuntu and OS X? I can prepare one for this branch and send PR to your `issue-1545b` branch. :)

**Comment by rprouse** [comment]
@jasonwilliams200OK, that would be great. I can take a PR to this branch. Need to make sure I have admin permissions on Travis to enable it :smile:

**Comment by rprouse** [comment]
@jasonwilliams200OK feel free to wait for me to get AppVeyor building if you want :smile:

**Comment by ghost** [comment]
@rprouse, sure, I have added the travis script in my fork, testing at the moment. https://github.com/jasonwilliams200OK/nunit.portable.agent/blob/5fb2c12a3f3036bd8eb1b8a37b8d7d3c28040dcf/.travis.yml :smile: 

---

Could you please apply this patch to appveyor script for clarity :)

``` diff
diff --git a/appveyor.yml b/appveyor.yml
index 77a80d2..f6e1ad7 100644
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -16,7 +16,11 @@ before_build:

 build_script:
   - cmd: dotnet build -c Release test/NUnit.Portable.Agent.Tests
+
+test_script:
   - cmd: dotnet run -c Release -p test/NUnit.Portable.Agent.Tests
+
+after_script:
   - cmd: dotnet pack -c Release src/NUnit.Portable.Agent

 test: off
```

---

(I am sure there must be a good reason, but still wondering) do we really need `imports` and using rc3 version of System.Console with rc2? Would be nice to keep all pacakges to rc2 and update to rc3 once CLI preview-2 is shipped.

**Comment by rprouse** [comment]
@jasonwilliams200OK Already ahead of you on the RC3 changes. Visual Studio auto-added them and I didn't notice.

I will apply your AppVeyor changes as soon as this build passes/fails just in case there are other changes.

**Comment by rprouse** [comment]
@jasonwilliams200OK you have a spelling mistake in your AppVeyor.yml, test_scrtip, and the commands are backwards for test_script and after_test. Fixed in my version, so don't include in your PR :smile:

**Comment by ghost** [comment]
Just edited the comment  :smile:

**Comment by rprouse** [comment]
@jasonwilliams200OK AppVeyor is passing :tada: 

I will merge this PR once you get your changes and I test in the `dotnet-test-nunit` project.

**Comment by ghost** [comment]
@rprouse, I see that the project.json of test project has imports due to the dependency on Nunit Lite? Is it a needed dependency? If so, can we port that project to dotnet core too so in Unix without mono, this project along with test project can build?

**Comment by rprouse** [comment]
@jasonwilliams200OK at the moment, nunitlite won't be ported until nunit.framework is also ported.

**Comment by ghost** [comment]
@rprouse, luckily it worked on Unix without mono! :smile:

**Comment by rprouse** [comment]
This is working, but it needs a net451 version for `dotnet-test-nunit` :frowning:

**Comment by ghost** [comment]
Can you please use `net45` instead. That would be bit more permissive.

For travis, this delta:

``` diff
-  - dotnet build -c $Configuration ./test/NUnit.Portable.Agent.Tests
+  - dotnet build -c $Configuration -f netcoreapp1.0 ./test/NUnit.Portable.Agent.Tests

 script:
   # Run tests
-  - dotnet run -c $Configuration -p ./test/NUnit.Portable.Agent.Tests
+  - dotnet run -c $Configuration -f netcoreapp1.0 -p ./test/NUnit.Portable.Agent.Tests
```

**Comment by rprouse** [comment]
Tested in a branch of `dotnet-test-nunit`. Finally merging :tada:

**Pull request merged**
