### PR TITLE
Test parameter parsing out of framework

### PR DESCRIPTION
**Pull request by jnm2**
Umbrella: https://github.com/nunit/nunit/issues/1941

Necessary part of https://github.com/nunit/dotnet-test-nunit/pull/96

### CODE REVIEW

**Comment by jnm2** [comment]
Not sure why Travis errors at `dotnet restore`:

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'Crypto' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.

**Comment by CharliePoole** [comment]
@rprouse Is this needed in the agent at all currently?

**Comment by rprouse** [comment]
@CharliePoole it is needed for his other PR and I am okay with including that functionality in the final beta of the .NET Core adapter. As I said, it will become obsolete soon, but I would like to get a few bugs fixed and released to hold people over until we have proper support in the engine and VS adapter.

**Comment by rprouse** [comment]
Travis failing is unrelated and has been happening for awhile.

**Pull request merged**
