### PR TITLE
Add travis CI for Linux and OSX testing

### PR DESCRIPTION
**Pull request by ghost**
Also using `dotnet` in `imports` instead.

### CODE REVIEW

**Comment by ghost** [comment]
@rprouse, the build status for this commit can be checked here: https://travis-ci.org/jasonwilliams200OK/nunit.portable.agent/builds/138145894. Can you please get official repository enabled on Travis as well: https://travis-ci.org/nunit/nunit.portable.agent?

**Comment by ghost** [comment]
Both AppVeyor for Windows + TravisCI for OSX (without mono, lang is c++) and Ubuntu (without mono, lang is c++) .. all green! :evergreen_tree: 

Note that using imports is a risky thing. It "tries" to map APIs to dotnet core surface area, but may end up requiring PCL if Nunit Lite changes in certain way. For long-term reliability, we would need to have NunitLite supporting NetStandard 1.3 and remove "imports".

**Comment by rprouse** [comment]
@jasonwilliams200OK I was just trying to enable nunit.portable.agent, but it isn't showing up in Travis. Clicking your link above, I get `The repository at nunit/nunit.portable.agent was not found.` and going through the organization on Travis, it says NUnit has 23 repos, but it is only showing 20 of them. Any ideas?

The only thing I can think of is I mistakenly created this repo under my account to start, then transferred ownership. It isn't showing up under my account either though. Any ideas?

**Comment by rprouse** [comment]
Never mind, I'm blind, I found the sync button. It looked disabled, but worked.

**Comment by rprouse** [comment]
@jasonwilliams200OK can you push a minor change to your branch to trigger a Travis build?

**Comment by ghost** [comment]
@rprouse, sure I ran my favorite command `git commit --amend; git push -f` and it worked! :smile:

**Comment by rprouse** [comment]
Woot, green is good :tada: :balloon: :cake: 

I am going to make Travis passing required for merge to master, then I will merge this. Thanks.

BTW, I've enabled Travis on `dotnet-test-nunit` if you are interested :smile:

**Comment by ghost** [comment]
Sure, as soon as we get sans-`imports` version there, I will make the travis script for dotnet-test-nunit and send the PR :smile:

**Comment by ghost** [comment]
@rprouse, can we get the new version of agent? I can then update dotnet-test-nunit project.json files and update my opened PR. :)

**Comment by rprouse** [comment]
I will do an update tomorrow, I just need to do a bit more testing first.

**Pull request merged**
